# Generated by Django 5.0.2 on 2024-03-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_participant_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='additional_phone_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
    ]
