# Generated by Django 5.0.2 on 2024-03-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_participant_additional_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='additional_phone_number',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone_number',
            field=models.CharField(max_length=18),
        ),
    ]
