# Generated by Django 5.0.2 on 2024-04-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_participant_additional_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='color',
            field=models.CharField(default='white', max_length=20),
        ),
    ]
