# Generated by Django 5.0.2 on 2024-04-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_participant_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
