# Generated by Django 5.0.2 on 2024-05-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_participant_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='additional_phone_number',
            field=models.CharField(blank=True, help_text='Доп. номер телефона', max_length=18),
        ),
        migrations.AlterField(
            model_name='participant',
            name='apartment_number',
            field=models.PositiveIntegerField(blank=True, help_text='Квартира'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='building',
            field=models.CharField(blank=True, help_text='Корпус/строение', max_length=255),
        ),
        migrations.AlterField(
            model_name='participant',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='district',
            field=models.CharField(blank=True, help_text='Район', max_length=255),
        ),
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.CharField(blank=True, help_text='Имя', max_length=255),
        ),
        migrations.AlterField(
            model_name='participant',
            name='house_number',
            field=models.CharField(blank=True, help_text='Номер дома', max_length=255),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_name',
            field=models.CharField(blank=True, help_text='Фамилия', max_length=255),
        ),
        migrations.AlterField(
            model_name='participant',
            name='patronymic',
            field=models.CharField(blank=True, help_text='Отчество', max_length=255),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Номер телефона', max_length=18),
        ),
        migrations.AlterField(
            model_name='participant',
            name='street',
            field=models.CharField(blank=True, help_text='Улица', max_length=255),
        ),
    ]
