# Generated by Django 5.0.2 on 2024-04-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0005_participantprofile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantprofile',
            name='number',
        ),
        migrations.AlterField(
            model_name='participantprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='participantprofile',
            name='first_name',
            field=models.CharField(blank=True, help_text='Имя', max_length=255),
        ),
        migrations.AlterField(
            model_name='participantprofile',
            name='last_name',
            field=models.CharField(blank=True, help_text='Фамилия', max_length=255),
        ),
        migrations.AlterField(
            model_name='participantprofile',
            name='patronymic',
            field=models.CharField(blank=True, help_text='Отчество', max_length=255),
        ),
        migrations.AlterField(
            model_name='participantprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Номер телефона', max_length=18),
        ),
    ]
